# Users
user_new:
    path: /user/new
    methods: [POST]
    controller: App\Controller\UserController::new

api_user_profile:
    path: api/user/profile
    methods: [GET]
    controller: App\Controller\UserController::profile

api_user_edit:
    path: api/user/edit/{id}
    methods: [PUT]
    controller: App\Controller\UserController::edit

api_user_delete:
    path: api/user/delete/{id}
    methods: [DELETE]
    controller: App\Controller\UserController::delete

# Authentication
api_login_check:
    path: /login_check
    methods: [POST]

# CategoriesPlaces
api_categories_places:
    path: api/categoriesPlaces
    methods: [GET]
    controller: App\Controller\CategoryPlacesController::categories

# Characters
api_character:
    path: api/character
    methods: [GET]
    controller: App\Controller\CharactersController::charactersByOwner

api_character_new:
    path: api/character/new
    methods: [POST]
    controller: App\Controller\CharactersController::new

api_character_edit:
    path: api/character/edit/{id}
    methods: [PUT]
    controller: App\Controller\CharactersController::edit

api_character_delete:
    path: api/character/delete/{id}
    methods: [DELETE]
    controller: App\Controller\CharactersController::delete
