# Users
user_new:
    path: /user/new
    methods: [POST]
    controller: App\Controller\UserController::new

api_user_profile:
    path: api/user/profile
    methods: [GET]
    controller: App\Controller\UserController::profile

api_user_edit:
    path: api/user/edit/{id}
    methods: [PATCH]
    controller: App\Controller\UserController::edit

api_user_edit_password:
    path: api/user/edit-password
    methods: [PATCH]
    controller: App\Controller\UserController::editPassword

api_user_delete:
    path: api/user/delete/{id}
    methods: [DELETE]
    controller: App\Controller\UserController::delete

# Authentication
api_login_check:
    path: /login_check
    methods: [POST]

# CategoriesPlaces
api_categories_places:
    path: api/categoriesPlaces
    methods: [GET]
    controller: App\Controller\CategoryPlacesController::categories

# Characters
api_character:
    path: api/character
    methods: [GET]
    controller: App\Controller\CharactersController::charactersByOwner

api_character_new:
    path: api/character/new
    methods: [POST]
    controller: App\Controller\CharactersController::new

api_character_edit:
    path: api/character/edit/{id}
    methods: [PUT]
    controller: App\Controller\CharactersController::edit

api_character_delete:
    path: api/character/delete/{id}
    methods: [DELETE]
    controller: App\Controller\CharactersController::delete

# Scenario
api_scenario:
    path: api/scenario
    methods: [GET]
    controller: App\Controller\ScenarioController::scenariosByOwner

api_scenario_other_owner:
    path: api/scenario/other
    methods: [GET]
    controller: App\Controller\ScenarioController::scenariosOfOtherOwnerThanCurrentUser

api_scenario_new:
    path: api/scenario/new
    methods: [POST]
    controller: App\Controller\ScenarioController::new

api_scenario_edit:
    path: api/scenario/edit/{id}
    methods: [PUT]
    controller: App\Controller\ScenarioController::edit

api_scenario_delete:
    path: api/scenario/delete/{id}
    methods: [DELETE]
    controller: App\Controller\ScenarioController::delete
