// Authentication
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// User
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

// Character
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const NEW_CHARACTER = 'NEW_CHARACTER';
export const NEW_CHARACTER_SUCCESS = 'NEW_CHARACTER_SUCCESS';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const EDIT_CHARACTER = 'EDIT_CHARACTER';
export const EDIT_CHARACTER_SUCCESS = 'EDIT_CHARACTER_SUCCESS';

// Scenario
export const GET_SCENARIOS = 'GET_SCENARIOS';
export const GET_SCENARIOS_SUCCESS = 'GET_SCENARIOS_SUCCESS';
export const NEW_SCENARIO = 'NEW_SCENARIO';
export const NEW_SCENARIO_SUCCESS = 'NEW_SCENARIO_SUCCESS';
export const EDIT_SCENARIO = 'EDIT_SCENARIO';
export const EDIT_SCENARIO_SUCCESS = 'EDIT_SCENARIO_SUCCESS';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';

// Place
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const NEW_PLACE = 'NEW_PLACE';
export const GET_PLACE = 'GET_PLACE';
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS';
export const EDIT_PLACE = 'EDIT_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

// Monster
export const NEW_MONSTER = 'NEW_MONSTER';
export const GET_MONSTER = 'GET_MONSTER';
export const GET_MONSTER_SUCCESS = 'GET_MONSTER_SUCCESS';
export const EDIT_MONSTER = 'EDIT_MONSTER';
export const DELETE_MONSTER = 'DELETE_MONSTER';

// Other
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
